package com.ssic.education.handle.pojo;

import java.util.Date;

public class ProDishes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.id
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.package_id
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private String packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.name
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.creator
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.create_time
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.updater
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.last_update_time
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_dishes.stat
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.id
     *
     * @return the value of t_pro_dishes.id
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.id
     *
     * @param id the value for t_pro_dishes.id
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.package_id
     *
     * @return the value of t_pro_dishes.package_id
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public String getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.package_id
     *
     * @param packageId the value for t_pro_dishes.package_id
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setPackageId(String packageId) {
        this.packageId = packageId == null ? null : packageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.name
     *
     * @return the value of t_pro_dishes.name
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.name
     *
     * @param name the value for t_pro_dishes.name
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.creator
     *
     * @return the value of t_pro_dishes.creator
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.creator
     *
     * @param creator the value for t_pro_dishes.creator
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.create_time
     *
     * @return the value of t_pro_dishes.create_time
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.create_time
     *
     * @param createTime the value for t_pro_dishes.create_time
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.updater
     *
     * @return the value of t_pro_dishes.updater
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.updater
     *
     * @param updater the value for t_pro_dishes.updater
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.last_update_time
     *
     * @return the value of t_pro_dishes.last_update_time
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.last_update_time
     *
     * @param lastUpdateTime the value for t_pro_dishes.last_update_time
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_dishes.stat
     *
     * @return the value of t_pro_dishes.stat
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_dishes.stat
     *
     * @param stat the value for t_pro_dishes.stat
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}