package com.ssic.education.handle.pojo;

import java.util.Date;

public class ProRecycleWaste {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.recycler_id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private String recyclerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.supplier_id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.recycle_date
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private Date recycleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.amount
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.recycler_name
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private String recyclerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.document_url
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private String documentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.create_time
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.last_update_time
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_recycle_waste.stat
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    private Short stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.id
     *
     * @return the value of t_pro_recycle_waste.id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.id
     *
     * @param id the value for t_pro_recycle_waste.id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.recycler_id
     *
     * @return the value of t_pro_recycle_waste.recycler_id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public String getRecyclerId() {
        return recyclerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.recycler_id
     *
     * @param recyclerId the value for t_pro_recycle_waste.recycler_id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setRecyclerId(String recyclerId) {
        this.recyclerId = recyclerId == null ? null : recyclerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.supplier_id
     *
     * @return the value of t_pro_recycle_waste.supplier_id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.supplier_id
     *
     * @param supplierId the value for t_pro_recycle_waste.supplier_id
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.recycle_date
     *
     * @return the value of t_pro_recycle_waste.recycle_date
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public Date getRecycleDate() {
        return recycleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.recycle_date
     *
     * @param recycleDate the value for t_pro_recycle_waste.recycle_date
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setRecycleDate(Date recycleDate) {
        this.recycleDate = recycleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.amount
     *
     * @return the value of t_pro_recycle_waste.amount
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.amount
     *
     * @param amount the value for t_pro_recycle_waste.amount
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.recycler_name
     *
     * @return the value of t_pro_recycle_waste.recycler_name
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public String getRecyclerName() {
        return recyclerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.recycler_name
     *
     * @param recyclerName the value for t_pro_recycle_waste.recycler_name
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setRecyclerName(String recyclerName) {
        this.recyclerName = recyclerName == null ? null : recyclerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.document_url
     *
     * @return the value of t_pro_recycle_waste.document_url
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public String getDocumentUrl() {
        return documentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.document_url
     *
     * @param documentUrl the value for t_pro_recycle_waste.document_url
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setDocumentUrl(String documentUrl) {
        this.documentUrl = documentUrl == null ? null : documentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.create_time
     *
     * @return the value of t_pro_recycle_waste.create_time
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.create_time
     *
     * @param createTime the value for t_pro_recycle_waste.create_time
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.last_update_time
     *
     * @return the value of t_pro_recycle_waste.last_update_time
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.last_update_time
     *
     * @param lastUpdateTime the value for t_pro_recycle_waste.last_update_time
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_recycle_waste.stat
     *
     * @return the value of t_pro_recycle_waste.stat
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public Short getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_recycle_waste.stat
     *
     * @param stat the value for t_pro_recycle_waste.stat
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    public void setStat(Short stat) {
        this.stat = stat;
    }
}