package com.ssic.education.handle.pojo;

public class ViewProSupplierWithBLOBs extends ViewProSupplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sup_sch_area_group.school_ids
     *
     * @mbggenerated Fri May 13 11:46:57 CST 2016
     */
    private String schoolIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sup_sch_area_group.school_names
     *
     * @mbggenerated Fri May 13 11:46:57 CST 2016
     */
    private String schoolNames;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sup_sch_area_group.school_ids
     *
     * @return the value of v_sup_sch_area_group.school_ids
     *
     * @mbggenerated Fri May 13 11:46:57 CST 2016
     */
    public String getSchoolIds() {
        return schoolIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sup_sch_area_group.school_ids
     *
     * @param schoolIds the value for v_sup_sch_area_group.school_ids
     *
     * @mbggenerated Fri May 13 11:46:57 CST 2016
     */
    public void setSchoolIds(String schoolIds) {
        this.schoolIds = schoolIds == null ? null : schoolIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sup_sch_area_group.school_names
     *
     * @return the value of v_sup_sch_area_group.school_names
     *
     * @mbggenerated Fri May 13 11:46:57 CST 2016
     */
    public String getSchoolNames() {
        return schoolNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sup_sch_area_group.school_names
     *
     * @param schoolNames the value for v_sup_sch_area_group.school_names
     *
     * @mbggenerated Fri May 13 11:46:57 CST 2016
     */
    public void setSchoolNames(String schoolNames) {
        this.schoolNames = schoolNames == null ? null : schoolNames.trim();
    }
}