package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.AddressSchool;
import com.ssic.education.common.pojo.AddressSchoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(AddressSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(AddressSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(AddressSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(AddressSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<AddressSchool> selectByExample(AddressSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    AddressSchool selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") AddressSchool record, @Param("example") AddressSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") AddressSchool record, @Param("example") AddressSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(AddressSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_address_school
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(AddressSchool record);
}