package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.CommentConfig;
import com.ssic.education.common.pojo.CommentConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(CommentConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(CommentConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(CommentConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(CommentConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<CommentConfig> selectByExample(CommentConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    CommentConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") CommentConfig record, @Param("example") CommentConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") CommentConfig record, @Param("example") CommentConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(CommentConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(CommentConfig record);
}