package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.CommentConfigScore;
import com.ssic.education.common.pojo.CommentConfigScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentConfigScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(CommentConfigScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(CommentConfigScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(CommentConfigScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(CommentConfigScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<CommentConfigScore> selectByExample(CommentConfigScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    CommentConfigScore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") CommentConfigScore record, @Param("example") CommentConfigScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") CommentConfigScore record, @Param("example") CommentConfigScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(CommentConfigScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_comment_config_score
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(CommentConfigScore record);
}