package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.EduInformation;
import com.ssic.education.common.pojo.EduInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int countByExample(EduInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int deleteByExample(EduInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int insert(EduInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int insertSelective(EduInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    List<EduInformation> selectByExample(EduInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    EduInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduInformation record, @Param("example") EduInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int updateByExample(@Param("record") EduInformation record, @Param("example") EduInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int updateByPrimaryKeySelective(EduInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    int updateByPrimaryKey(EduInformation record);
}