package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.EduSupplierReceiver;
import com.ssic.education.common.pojo.EduSupplierReceiverExample;
import com.ssic.education.common.pojo.EduSupplierReceiverKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduSupplierReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int countByExample(EduSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int deleteByExample(EduSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int deleteByPrimaryKey(EduSupplierReceiverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int insert(EduSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int insertSelective(EduSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    List<EduSupplierReceiver> selectByExample(EduSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    EduSupplierReceiver selectByPrimaryKey(EduSupplierReceiverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduSupplierReceiver record, @Param("example") EduSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int updateByExample(@Param("record") EduSupplierReceiver record, @Param("example") EduSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int updateByPrimaryKeySelective(EduSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:26:41 CST 2016
     */
    int updateByPrimaryKey(EduSupplierReceiver record);
}