package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.EduStudentGuardian;
import com.ssic.education.common.pojo.EduStudentGuardianExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduStudentGuardianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int countByExample(EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int deleteByExample(EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int insert(EduStudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int insertSelective(EduStudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    List<EduStudentGuardian> selectByExample(EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    EduStudentGuardian selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduStudentGuardian record, @Param("example") EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int updateByExample(@Param("record") EduStudentGuardian record, @Param("example") EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int updateByPrimaryKeySelective(EduStudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Wed May 11 10:54:36 CST 2016
     */
    int updateByPrimaryKey(EduStudentGuardian record);
}