package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.EduTaskReceive;
import com.ssic.education.common.pojo.EduTaskReceiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduTaskReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int countByExample(EduTaskReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int deleteByExample(EduTaskReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int insert(EduTaskReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int insertSelective(EduTaskReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    List<EduTaskReceive> selectByExample(EduTaskReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    EduTaskReceive selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduTaskReceive record, @Param("example") EduTaskReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int updateByExample(@Param("record") EduTaskReceive record, @Param("example") EduTaskReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int updateByPrimaryKeySelective(EduTaskReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_task_receive
     *
     * @mbggenerated Fri May 20 15:14:56 CST 2016
     */
    int updateByPrimaryKey(EduTaskReceive record);
}