package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.EveryMaterialHistory;
import com.ssic.education.common.pojo.EveryMaterialHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EveryMaterialHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(EveryMaterialHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(EveryMaterialHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(EveryMaterialHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(EveryMaterialHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<EveryMaterialHistory> selectByExample(EveryMaterialHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    EveryMaterialHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") EveryMaterialHistory record, @Param("example") EveryMaterialHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") EveryMaterialHistory record, @Param("example") EveryMaterialHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(EveryMaterialHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_every_material_history
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(EveryMaterialHistory record);
}