package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.GradeCarteType;
import com.ssic.education.common.pojo.GradeCarteTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradeCarteTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(GradeCarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(GradeCarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(GradeCarteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(GradeCarteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<GradeCarteType> selectByExample(GradeCarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    GradeCarteType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") GradeCarteType record, @Param("example") GradeCarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") GradeCarteType record, @Param("example") GradeCarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(GradeCarteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_grade_carte_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(GradeCarteType record);
}