package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.Practitioners;
import com.ssic.education.common.pojo.PractitionersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PractitionersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int countByExample(PractitionersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int deleteByExample(PractitionersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int insert(Practitioners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int insertSelective(Practitioners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    List<Practitioners> selectByExample(PractitionersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    Practitioners selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") Practitioners record, @Param("example") PractitionersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByExample(@Param("record") Practitioners record, @Param("example") PractitionersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByPrimaryKeySelective(Practitioners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_practitioners
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByPrimaryKey(Practitioners record);
}