package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.ProSupplier;
import com.ssic.education.common.pojo.ProSupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int countByExample(ProSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int deleteByExample(ProSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int insert(ProSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int insertSelective(ProSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    List<ProSupplier> selectByExample(ProSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    ProSupplier selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProSupplier record, @Param("example") ProSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int updateByExample(@Param("record") ProSupplier record, @Param("example") ProSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int updateByPrimaryKeySelective(ProSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier
     *
     * @mbggenerated Mon May 23 10:43:10 CST 2016
     */
    int updateByPrimaryKey(ProSupplier record);
}