package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.ProSupplierReceiver;
import com.ssic.education.common.pojo.ProSupplierReceiverExample;
import com.ssic.education.common.pojo.ProSupplierReceiverKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProSupplierReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int countByExample(ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int deleteByExample(ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int deleteByPrimaryKey(ProSupplierReceiverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int insert(ProSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int insertSelective(ProSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    List<ProSupplierReceiver> selectByExample(ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    ProSupplierReceiver selectByPrimaryKey(ProSupplierReceiverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProSupplierReceiver record, @Param("example") ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int updateByExample(@Param("record") ProSupplierReceiver record, @Param("example") ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int updateByPrimaryKeySelective(ProSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
     * @mbggenerated Sat May 21 17:43:06 CST 2016
     */
    int updateByPrimaryKey(ProSupplierReceiver record);
}