package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.RoleProject;
import com.ssic.education.common.pojo.RoleProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int countByExample(RoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int deleteByExample(RoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int insert(RoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int insertSelective(RoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    List<RoleProject> selectByExample(RoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    RoleProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") RoleProject record, @Param("example") RoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByExample(@Param("record") RoleProject record, @Param("example") RoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByPrimaryKeySelective(RoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_project
     *
     * @mbggenerated Wed May 11 10:07:25 CST 2016
     */
    int updateByPrimaryKey(RoleProject record);
}