package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.SensitiveValveConf;
import com.ssic.education.common.pojo.SensitiveValveConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensitiveValveConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(SensitiveValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(SensitiveValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(SensitiveValveConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(SensitiveValveConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<SensitiveValveConf> selectByExample(SensitiveValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    SensitiveValveConf selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") SensitiveValveConf record, @Param("example") SensitiveValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") SensitiveValveConf record, @Param("example") SensitiveValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(SensitiveValveConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive_valve_conf
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(SensitiveValveConf record);
}