package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.TodayMenuType;
import com.ssic.education.common.pojo.TodayMenuTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodayMenuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(TodayMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(TodayMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(TodayMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(TodayMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<TodayMenuType> selectByExample(TodayMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    TodayMenuType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") TodayMenuType record, @Param("example") TodayMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") TodayMenuType record, @Param("example") TodayMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(TodayMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_today_menu_type
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(TodayMenuType record);
}