package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.TransportTask;
import com.ssic.education.common.pojo.TransportTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransportTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(TransportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(TransportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(TransportTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(TransportTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<TransportTask> selectByExample(TransportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    TransportTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") TransportTask record, @Param("example") TransportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") TransportTask record, @Param("example") TransportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(TransportTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_task
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(TransportTask record);
}