package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.TransportDriver;
import com.ssic.education.common.pojo.TransportDriverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransportDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(TransportDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(TransportDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(TransportDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(TransportDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<TransportDriver> selectByExample(TransportDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    TransportDriver selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") TransportDriver record, @Param("example") TransportDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") TransportDriver record, @Param("example") TransportDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(TransportDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_driver
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(TransportDriver record);
}