package com.ssic.education.common.mapper;

import com.ssic.education.common.pojo.TransportDest;
import com.ssic.education.common.pojo.TransportDestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransportDestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(TransportDestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(TransportDestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(TransportDest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(TransportDest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<TransportDest> selectByExample(TransportDestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    TransportDest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") TransportDest record, @Param("example") TransportDestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") TransportDest record, @Param("example") TransportDestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(TransportDest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_transport_dest
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(TransportDest record);
}