package com.ssic.education.wecaht.handle.mapper;

import com.ssic.education.wecaht.handle.pojo.EduParent;
import com.ssic.education.wecaht.handle.pojo.EduParentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int countByExample(EduParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int deleteByExample(EduParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int insert(EduParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int insertSelective(EduParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    List<EduParent> selectByExample(EduParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    EduParent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduParent record, @Param("example") EduParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int updateByExample(@Param("record") EduParent record, @Param("example") EduParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int updateByPrimaryKeySelective(EduParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent
     *
     * @mbggenerated Sat May 21 14:37:45 CST 2016
     */
    int updateByPrimaryKey(EduParent record);
}