package com.ssic.education.handle.mapper;

import com.ssic.education.handle.pojo.EduInformationList;
import com.ssic.education.handle.pojo.EduInformationListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduInformationListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int countByExample(EduInformationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int deleteByExample(EduInformationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int insert(EduInformationList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int insertSelective(EduInformationList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    List<EduInformationList> selectByExample(EduInformationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    EduInformationList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduInformationList record, @Param("example") EduInformationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByExample(@Param("record") EduInformationList record, @Param("example") EduInformationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByPrimaryKeySelective(EduInformationList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_information_list
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByPrimaryKey(EduInformationList record);
}