package com.ssic.education.handle.mapper;

import com.ssic.education.handle.pojo.EduParentPackComment;
import com.ssic.education.handle.pojo.EduParentPackCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduParentPackCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int countByExample(EduParentPackCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int deleteByExample(EduParentPackCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int insert(EduParentPackComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int insertSelective(EduParentPackComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    List<EduParentPackComment> selectByExample(EduParentPackCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    EduParentPackComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduParentPackComment record, @Param("example") EduParentPackCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int updateByExample(@Param("record") EduParentPackComment record, @Param("example") EduParentPackCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int updateByPrimaryKeySelective(EduParentPackComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_parent_pack_comment
     *
     * @mbggenerated Sun May 29 16:27:13 CST 2016
     */
    int updateByPrimaryKey(EduParentPackComment record);
}