package com.ssic.education.handle.mapper;

import com.ssic.education.handle.pojo.EduSchoolSupplier;
import com.ssic.education.handle.pojo.EduSchoolSupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduSchoolSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int countByExample(EduSchoolSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int deleteByExample(EduSchoolSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int insert(EduSchoolSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int insertSelective(EduSchoolSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    List<EduSchoolSupplier> selectByExample(EduSchoolSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    EduSchoolSupplier selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduSchoolSupplier record, @Param("example") EduSchoolSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByExample(@Param("record") EduSchoolSupplier record, @Param("example") EduSchoolSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByPrimaryKeySelective(EduSchoolSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier
     *
     * @mbggenerated Tue Jun 07 10:44:38 CST 2016
     */
    int updateByPrimaryKey(EduSchoolSupplier record);
}