package com.ssic.education.handle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ssic.education.handle.pojo.EduStudentGuardian;
import com.ssic.education.handle.pojo.EduStudentGuardianExample;

public interface EduStudentGuardianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int countByExample(EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int deleteByExample(EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int insert(EduStudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int insertSelective(EduStudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    List<EduStudentGuardian> selectByExample(EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    EduStudentGuardian selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduStudentGuardian record, @Param("example") EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByExample(@Param("record") EduStudentGuardian record, @Param("example") EduStudentGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByPrimaryKeySelective(EduStudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_student_guardian
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByPrimaryKey(EduStudentGuardian record);
}