package com.ssic.education.handle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ssic.education.handle.pojo.ProAddresses;
import com.ssic.education.handle.pojo.ProAddressesExample;

public interface ProAddressesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int countByExample(ProAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int deleteByExample(ProAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int insert(ProAddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int insertSelective(ProAddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    List<ProAddresses> selectByExample(ProAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    ProAddresses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProAddresses record, @Param("example") ProAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByExample(@Param("record") ProAddresses record, @Param("example") ProAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByPrimaryKeySelective(ProAddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_addresses
     *
     * @mbggenerated Thu May 26 19:23:18 CST 2016
     */
    int updateByPrimaryKey(ProAddresses record);
}