package com.ssic.education.handle.mapper;

import com.ssic.education.handle.pojo.ProSupplierReceiver;
import com.ssic.education.handle.pojo.ProSupplierReceiverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProSupplierReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int countByExample(ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int deleteByExample(ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int insert(ProSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int insertSelective(ProSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    List<ProSupplierReceiver> selectByExample(ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    ProSupplierReceiver selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int updateByExampleSelective(@Param("record") ProSupplierReceiver record, @Param("example") ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int updateByExample(@Param("record") ProSupplierReceiver record, @Param("example") ProSupplierReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int updateByPrimaryKeySelective(ProSupplierReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_supplier_receiver
     *
<<<<<<< HEAD
     * @mbggenerated Tue Jun 07 15:20:01 CST 2016
=======
     * @mbggenerated Tue Jun 07 16:02:25 CST 2016
>>>>>>> branch 'master' of http://192.168.1.231/group-one/education.git
     */
    int updateByPrimaryKey(ProSupplierReceiver record);
}
