package com.ssic.education.handle.mapper;

import com.ssic.education.handle.pojo.ProUsers;
import com.ssic.education.handle.pojo.ProUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int countByExample(ProUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int deleteByExample(ProUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int insert(ProUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int insertSelective(ProUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    List<ProUsers> selectByExample(ProUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    ProUsers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProUsers record, @Param("example") ProUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int updateByExample(@Param("record") ProUsers record, @Param("example") ProUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int updateByPrimaryKeySelective(ProUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_users
     *
     * @mbggenerated Tue Jun 07 16:12:11 CST 2016
     */
    int updateByPrimaryKey(ProUsers record);
}