package com.ssic.education.provider.mapper;

import com.ssic.education.provider.pojo.ProMenu;
import com.ssic.education.provider.pojo.ProMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int countByExample(ProMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int deleteByExample(ProMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int insert(ProMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int insertSelective(ProMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    List<ProMenu> selectByExample(ProMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    ProMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProMenu record, @Param("example") ProMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByExample(@Param("record") ProMenu record, @Param("example") ProMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByPrimaryKeySelective(ProMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByPrimaryKey(ProMenu record);
}