package com.ssic.education.provider.mapper;

import com.ssic.education.provider.pojo.ProRoleProject;
import com.ssic.education.provider.pojo.ProRoleProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProRoleProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int countByExample(ProRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int deleteByExample(ProRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int insert(ProRoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int insertSelective(ProRoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    List<ProRoleProject> selectByExample(ProRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    ProRoleProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProRoleProject record, @Param("example") ProRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByExample(@Param("record") ProRoleProject record, @Param("example") ProRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByPrimaryKeySelective(ProRoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_role_project
     *
     * @mbggenerated Thu May 12 14:24:24 CST 2016
     */
    int updateByPrimaryKey(ProRoleProject record);
}