package com.ssic.education.provider.mapper;

import com.ssic.education.provider.pojo.ProRoleMenu;
import com.ssic.education.provider.pojo.ProRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int countByExample(ProRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int deleteByExample(ProRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int insert(ProRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int insertSelective(ProRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    List<ProRoleMenu> selectByExample(ProRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    ProRoleMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProRoleMenu record, @Param("example") ProRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByExample(@Param("record") ProRoleMenu record, @Param("example") ProRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByPrimaryKeySelective(ProRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_role_menu
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByPrimaryKey(ProRoleMenu record);
}