package com.ssic.education.provider.mapper;

import com.ssic.education.provider.pojo.ProUserRole;
import com.ssic.education.provider.pojo.ProUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int countByExample(ProUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int deleteByExample(ProUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int insert(ProUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int insertSelective(ProUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    List<ProUserRole> selectByExample(ProUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    ProUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProUserRole record, @Param("example") ProUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByExample(@Param("record") ProUserRole record, @Param("example") ProUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByPrimaryKeySelective(ProUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_admin_users_role
     *
     * @mbggenerated Wed May 11 11:05:19 CST 2016
     */
    int updateByPrimaryKey(ProUserRole record);
}