package com.ssic.education.pro.mapper;

import com.ssic.education.pro.pojo.ProRecycleOil;
import com.ssic.education.pro.pojo.ProRecycleOilExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProRecycleOilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int countByExample(ProRecycleOilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int deleteByExample(ProRecycleOilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int insert(ProRecycleOil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int insertSelective(ProRecycleOil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    List<ProRecycleOil> selectByExample(ProRecycleOilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    ProRecycleOil selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProRecycleOil record, @Param("example") ProRecycleOilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByExample(@Param("record") ProRecycleOil record, @Param("example") ProRecycleOilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByPrimaryKeySelective(ProRecycleOil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_recycle_oil
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByPrimaryKey(ProRecycleOil record);
}