package com.ssic.education.pro.mapper;

import com.ssic.education.pro.pojo.ProSchoolWare;
import com.ssic.education.pro.pojo.ProSchoolWareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProSchoolWareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int countByExample(ProSchoolWareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int deleteByExample(ProSchoolWareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int insert(ProSchoolWare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int insertSelective(ProSchoolWare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    List<ProSchoolWare> selectByExample(ProSchoolWareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    ProSchoolWare selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProSchoolWare record, @Param("example") ProSchoolWareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByExample(@Param("record") ProSchoolWare record, @Param("example") ProSchoolWareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByPrimaryKeySelective(ProSchoolWare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_school_ware
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByPrimaryKey(ProSchoolWare record);
}