package com.ssic.education.pro.mapper;

import com.ssic.education.pro.pojo.ProWasteRecycler;
import com.ssic.education.pro.pojo.ProWasteRecyclerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProWasteRecyclerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int countByExample(ProWasteRecyclerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int deleteByExample(ProWasteRecyclerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int insert(ProWasteRecycler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int insertSelective(ProWasteRecycler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    List<ProWasteRecycler> selectByExample(ProWasteRecyclerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    ProWasteRecycler selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProWasteRecycler record, @Param("example") ProWasteRecyclerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByExample(@Param("record") ProWasteRecycler record, @Param("example") ProWasteRecyclerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByPrimaryKeySelective(ProWasteRecycler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_waste_recycler
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    int updateByPrimaryKey(ProWasteRecycler record);
}