package com.ssic.test.common.mapper;

import com.ssic.test.common.pojo.SchoolSupplierRel;
import com.ssic.test.common.pojo.SchoolSupplierRelExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SchoolSupplierRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(SchoolSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(SchoolSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(SchoolSupplierRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(SchoolSupplierRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<SchoolSupplierRel> selectByExample(SchoolSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    SchoolSupplierRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") SchoolSupplierRel record, @Param("example") SchoolSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") SchoolSupplierRel record, @Param("example") SchoolSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(SchoolSupplierRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(SchoolSupplierRel record);
}