package com.ssic.test.common.mapper;

import com.ssic.test.common.pojo.SchoolMaterialSupplierRel;
import com.ssic.test.common.pojo.SchoolMaterialSupplierRelExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SchoolMaterialSupplierRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(SchoolMaterialSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(SchoolMaterialSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(SchoolMaterialSupplierRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(SchoolMaterialSupplierRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<SchoolMaterialSupplierRel> selectByExample(SchoolMaterialSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    SchoolMaterialSupplierRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") SchoolMaterialSupplierRel record, @Param("example") SchoolMaterialSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") SchoolMaterialSupplierRel record, @Param("example") SchoolMaterialSupplierRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(SchoolMaterialSupplierRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_school_material_supplier_rel
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(SchoolMaterialSupplierRel record);
}