package com.ssic.test.common.mapper;

import com.ssic.test.common.pojo.Sensitive;
import com.ssic.test.common.pojo.SensitiveExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SensitiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int countByExample(SensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByExample(SensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insert(Sensitive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int insertSelective(Sensitive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    List<Sensitive> selectByExample(SensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    Sensitive selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sensitive record, @Param("example") SensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByExample(@Param("record") Sensitive record, @Param("example") SensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKeySelective(Sensitive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_sensitive
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    int updateByPrimaryKey(Sensitive record);
}