package com.ssic.education.government.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ssic.education.government.pojo.EduMenu;
import com.ssic.education.government.pojo.EduMenuExample;

public interface EduMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int countByExample(EduMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int deleteByExample(EduMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int insert(EduMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int insertSelective(EduMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    List<EduMenu> selectByExample(EduMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    EduMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduMenu record, @Param("example") EduMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByExample(@Param("record") EduMenu record, @Param("example") EduMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByPrimaryKeySelective(EduMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByPrimaryKey(EduMenu record);
}