package com.ssic.education.government.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ssic.education.government.pojo.EduRoleProject;
import com.ssic.education.government.pojo.EduRoleProjectExample;

public interface EduRoleProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int countByExample(EduRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int deleteByExample(EduRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int insert(EduRoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int insertSelective(EduRoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    List<EduRoleProject> selectByExample(EduRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    EduRoleProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduRoleProject record, @Param("example") EduRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByExample(@Param("record") EduRoleProject record, @Param("example") EduRoleProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByPrimaryKeySelective(EduRoleProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_project
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByPrimaryKey(EduRoleProject record);
}