package com.ssic.education.common.dto;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

@Data
public class EduCommitteeDto implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_committee.id
     *
     * @mbggenerated Mon May 16 10:43:54 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_committee.name
     *
     * @mbggenerated Mon May 16 10:43:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_committee.create_time
     *
     * @mbggenerated Mon May 16 10:43:54 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_committee.last_update_time
     *
     * @mbggenerated Mon May 16 10:43:54 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_committee.stat
     *
     * @mbggenerated Mon May 16 10:43:54 CST 2016
     */
    private Short stat;

}
