package com.ssic.education.pro.pojo;

import java.util.Date;

public class ProLedgerMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.action_date
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private Date actionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.receiver_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.receiver_name
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.user_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.source_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.ware_batch_no
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private String wareBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.haul_status
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private Integer haulStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.create_time
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.last_update_time
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_ledger_master.stat
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.id
     *
     * @return the value of t_pro_ledger_master.id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.id
     *
     * @param id the value for t_pro_ledger_master.id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.action_date
     *
     * @return the value of t_pro_ledger_master.action_date
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public Date getActionDate() {
        return actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.action_date
     *
     * @param actionDate the value for t_pro_ledger_master.action_date
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.receiver_id
     *
     * @return the value of t_pro_ledger_master.receiver_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.receiver_id
     *
     * @param receiverId the value for t_pro_ledger_master.receiver_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.receiver_name
     *
     * @return the value of t_pro_ledger_master.receiver_name
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.receiver_name
     *
     * @param receiverName the value for t_pro_ledger_master.receiver_name
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.user_id
     *
     * @return the value of t_pro_ledger_master.user_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.user_id
     *
     * @param userId the value for t_pro_ledger_master.user_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.source_id
     *
     * @return the value of t_pro_ledger_master.source_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.source_id
     *
     * @param sourceId the value for t_pro_ledger_master.source_id
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.ware_batch_no
     *
     * @return the value of t_pro_ledger_master.ware_batch_no
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public String getWareBatchNo() {
        return wareBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.ware_batch_no
     *
     * @param wareBatchNo the value for t_pro_ledger_master.ware_batch_no
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setWareBatchNo(String wareBatchNo) {
        this.wareBatchNo = wareBatchNo == null ? null : wareBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.haul_status
     *
     * @return the value of t_pro_ledger_master.haul_status
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public Integer getHaulStatus() {
        return haulStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.haul_status
     *
     * @param haulStatus the value for t_pro_ledger_master.haul_status
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setHaulStatus(Integer haulStatus) {
        this.haulStatus = haulStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.create_time
     *
     * @return the value of t_pro_ledger_master.create_time
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.create_time
     *
     * @param createTime the value for t_pro_ledger_master.create_time
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.last_update_time
     *
     * @return the value of t_pro_ledger_master.last_update_time
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.last_update_time
     *
     * @param lastUpdateTime the value for t_pro_ledger_master.last_update_time
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_ledger_master.stat
     *
     * @return the value of t_pro_ledger_master.stat
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_ledger_master.stat
     *
     * @param stat the value for t_pro_ledger_master.stat
     *
     * @mbggenerated Thu May 26 11:08:24 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}