package com.ssic.education.government.mapper;

import com.ssic.education.government.pojo.EduMenuType;
import com.ssic.education.government.pojo.EduMenuTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduMenuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int countByExample(EduMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int deleteByExample(EduMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int insert(EduMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int insertSelective(EduMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    List<EduMenuType> selectByExample(EduMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    EduMenuType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduMenuType record, @Param("example") EduMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int updateByExample(@Param("record") EduMenuType record, @Param("example") EduMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int updateByPrimaryKeySelective(EduMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_admin_menu_type
     *
     * @mbggenerated Wed May 11 11:02:34 CST 2016
     */
    int updateByPrimaryKey(EduMenuType record);
}