package com.ssic.education.government.mapper;

import com.ssic.education.government.pojo.EduRoleMenu;
import com.ssic.education.government.pojo.EduRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int countByExample(EduRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int deleteByExample(EduRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int insert(EduRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int insertSelective(EduRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    List<EduRoleMenu> selectByExample(EduRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    EduRoleMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduRoleMenu record, @Param("example") EduRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByExample(@Param("record") EduRoleMenu record, @Param("example") EduRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByPrimaryKeySelective(EduRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_role_menu
     *
     * @mbggenerated Thu May 12 14:27:54 CST 2016
     */
    int updateByPrimaryKey(EduRoleMenu record);
}