package com.ssic.test.common.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.school_id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.comment
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.user_open_id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private String userOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.create_time
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.last_update_time
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.stat
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_edu_comment.user_open_icon
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    private String userOpenIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.id
     *
     * @return the value of t_edu_comment.id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.id
     *
     * @param id the value for t_edu_comment.id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.school_id
     *
     * @return the value of t_edu_comment.school_id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.school_id
     *
     * @param schoolId the value for t_edu_comment.school_id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.comment
     *
     * @return the value of t_edu_comment.comment
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.comment
     *
     * @param comment the value for t_edu_comment.comment
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.user_open_id
     *
     * @return the value of t_edu_comment.user_open_id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public String getUserOpenId() {
        return userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.user_open_id
     *
     * @param userOpenId the value for t_edu_comment.user_open_id
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setUserOpenId(String userOpenId) {
        this.userOpenId = userOpenId == null ? null : userOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.create_time
     *
     * @return the value of t_edu_comment.create_time
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.create_time
     *
     * @param createTime the value for t_edu_comment.create_time
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.last_update_time
     *
     * @return the value of t_edu_comment.last_update_time
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.last_update_time
     *
     * @param lastUpdateTime the value for t_edu_comment.last_update_time
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.stat
     *
     * @return the value of t_edu_comment.stat
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.stat
     *
     * @param stat the value for t_edu_comment.stat
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_edu_comment.user_open_icon
     *
     * @return the value of t_edu_comment.user_open_icon
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public String getUserOpenIcon() {
        return userOpenIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_edu_comment.user_open_icon
     *
     * @param userOpenIcon the value for t_edu_comment.user_open_icon
     *
     * @mbggenerated Tue Mar 15 11:16:51 CST 2016
     */
    public void setUserOpenIcon(String userOpenIcon) {
        this.userOpenIcon = userOpenIcon == null ? null : userOpenIcon.trim();
    }
}