package com.ssic.education.admin.mapper;

import com.ssic.education.admin.pojo.AdminUsers;
import com.ssic.education.admin.pojo.AdminUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int countByExample(AdminUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int deleteByExample(AdminUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int insert(AdminUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int insertSelective(AdminUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    List<AdminUsers> selectByExample(AdminUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    AdminUsers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") AdminUsers record, @Param("example") AdminUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int updateByExample(@Param("record") AdminUsers record, @Param("example") AdminUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int updateByPrimaryKeySelective(AdminUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_users
     *
     * @mbggenerated Tue Mar 15 11:13:39 CST 2016
     */
    int updateByPrimaryKey(AdminUsers record);
}