package com.ssic.education.edu.mapper;

import com.ssic.education.edu.pojo.EduGuardian;
import com.ssic.education.edu.pojo.EduGuardianExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduGuardianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int countByExample(EduGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int deleteByExample(EduGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int insert(EduGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int insertSelective(EduGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    List<EduGuardian> selectByExample(EduGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    EduGuardian selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") EduGuardian record, @Param("example") EduGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int updateByExample(@Param("record") EduGuardian record, @Param("example") EduGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int updateByPrimaryKeySelective(EduGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_edu_guardian
     *
     * @mbggenerated Thu May 26 11:08:19 CST 2016
     */
    int updateByPrimaryKey(EduGuardian record);
}